project_id = "hraxkydlctyoflcilgnz"

[functions.verify-pin]
verify_jwt = false

[functions.kiosk]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.task-reminders]
verify_jwt = false
