ALTER TABLE public.company_settings
  ADD COLUMN IF NOT EXISTS rc text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS if_number text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cnss text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS patente text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone2 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone_dir text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone_gsm text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS logo_size text NOT NULL DEFAULT 'medium';